function exportToPDF() {
  try {
    const results = Array.from(document.querySelectorAll('.result-card')).map(card => {
      const url = card.querySelector('.url').textContent;
      const status = card.querySelector('.status-text').textContent.trim();
      const statusTooltip = card.querySelector('.status-badge').getAttribute('data-tooltip');
      const details = card.querySelector('.details').innerHTML.replace(/<br>/g, '; ');
      const redirectChain = details.includes('Redirect Chain') ? details.split('; ').find(d => d.startsWith('Redirect Chain')).replace('Redirect Chain: ', '') : '-';
      const error = details.includes('Redirect Chain') ? details.split('; ').filter(d => !d.startsWith('Redirect Chain')).join('; ') : details || '-';
      const timestamp = card.querySelector('.timestamp').textContent.replace('Scanned: ', '');
      return { url, status, statusTooltip, redirectChain, error, timestamp };
    });

    const healthScore = document.getElementById('health-score').textContent;
    const summary = {
      total: document.getElementById('summary-total').textContent,
      ok: document.getElementById('summary-ok').textContent,
      redirects: document.getElementById('summary-redirects').textContent,
      broken: document.getElementById('summary-broken').textContent,
      risky: document.getElementById('summary-risky').textContent
    };

    const generatedDate = new Date().toLocaleString();
    const fileDate = new Date().toISOString().slice(0, 10).replace(/-/g, '');

    const exportContent = document.createElement('div');
    exportContent.style.padding = '30px';
    exportContent.style.fontFamily = '"Poppins", sans-serif';
    exportContent.style.color = '#1A1C23';
    exportContent.style.background = '#FFFFFF';
    exportContent.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <img src="assets/logo.svg" alt="LinkCheckr Pro Logo" style="width: 60px; height: 60px; margin-bottom: 10px;">
        <h1 style="font-size: 28px; font-weight: 800; color: #3D5AFE; margin: 0;">LinkCheckr Pro Scan Report</h1>
        <p style="font-size: 16px; font-weight: 500; color: #1A1C23;">Generated by SIAM on ${generatedDate}</p>
        <p style="font-size: 14px; color: #3D5AFE;">
          <a href="https://m-siam.github.io/LinkChecker-Pro/" style="color: #3D5AFE; text-decoration: none;">https://m-siam.github.io/LinkChecker-Pro/</a>
        </p>
        <p style="font-size: 12px; color: #6B7280; margin-top: 5px;">© 2025 SIAM. All rights reserved.</p>
      </div>
      <h2 style="font-size: 20px; font-weight: 700; color: #3D5AFE; margin-bottom: 15px;">Scan Summary</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 14px; margin-bottom: 30px;">
        <tr style="background: #F1F3F5;">
          <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left;">Metric</th>
          <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left;">Value</th>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">Link Health</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${healthScore}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">Total Links</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${summary.total}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">OK</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${summary.ok}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">Redirects</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${summary.redirects}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">Broken</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${summary.broken}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">Risky</td>
          <td style="padding: 10px; border: 1px solid #E0E0E0;">${summary.risky}</td>
        </tr>
      </table>
      <h2 style="font-size: 20px; font-weight: 700; color: #3D5AFE; margin-bottom: 15px;">Detailed Results</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
        <thead>
          <tr style="background: #F1F3F5;">
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 30%;">URL</th>
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 10%;">Status</th>
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 20%;">Status Description</th>
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 20%;">Redirect Chain</th>
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 10%;">Error</th>
            <th style="padding: 10px; border: 1px solid #E0E0E0; text-align: left; width: 10%;">Timestamp</th>
          </tr>
        </thead>
        <tbody>
          ${results.map(result => `
            <tr>
              <td style="padding: 10px; border: 1px solid #E0E0E0; word-break: break-all;">${result.url}</td>
              <td style="padding: 10px; border: 1px solid #E0E0E0;">${result.status}</td>
              <td style="padding: 10px; border: 1px solid #E0E0E0;">${result.statusTooltip}</td>
              <td style="padding: 10px; border: 1px solid #E0E0E0;">${result.redirectChain}</td>
              <td style="padding: 10px; border: 1px solid #E0E0E0;">${result.error}</td>
              <td style="padding: 10px; border: 1px solid #E0E0E0;">${result.timestamp}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;

    const opt = {
      margin: [0.5, 0.5, 0.5, 0.5],
      filename: `LinkCheckr_Pro_Scan_${fileDate}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().from(exportContent).set(opt).save().catch(err => {
      console.error('PDF export failed:', err);
      showToast('Failed to export PDF. Please try again.', 'error');
    });
  } catch (err) {
    console.error('PDF export error:', err);
    showToast('Failed to export PDF. Please try again.', 'error');
  }
}
