function exportToPDF() {
  const results = Array.from(document.querySelectorAll('.result-card')).map(card => {
    const url = card.querySelector('.url').textContent;
    const status = card.querySelector('.status-tag').textContent.trim().split('\n')[1];
    const details = card.querySelector('.details').innerHTML.replace(/<br>/g, '; ');
    const insights = card.querySelector('.insights').textContent;
    const timestamp = card.querySelector('.timestamp').textContent;
    return { url, status, details, insights, timestamp };
  });

  const healthScore = document.getElementById('health-score').textContent;
  const summary = {
    total: document.getElementById('summary-total').textContent,
    ok: document.getElementById('summary-ok').textContent,
    redirects: document.getElementById('summary-redirects').textContent,
    broken: document.getElementById('summary-broken').textContent,
    risky: document.getElementById('summary-risky').textContent
  };

  const exportContent = document.createElement('div');
  exportContent.style.padding = '30px';
  exportContent.style.fontFamily = 'Poppins, sans-serif';
  exportContent.style.color = '#1E293B';
  exportContent.innerHTML = `
    <div style="text-align: center; margin-bottom: 30px;">
      <img src="assets/logo.svg" alt="LinkCheckr Pro Logo" style="width: 60px; height: 60px;">
      <h1 style="font-size: 28px; font-weight: 800; color: #6366F1;">LinkCheckr Pro Scan Report</h1>
      <p style="font-size: 16px;">Generated by SIAM on ${new Date().toLocaleString()}</p>
      <p style="font-size: 16px;">Website: <a href="https://m-siam.github.io/LinkChecker-Pro/">https://m-siam.github.io/LinkChecker-Pro/</a></p>
      <p style="font-size: 14px; color: #6B7280;">© 2025 SIAM. All rights reserved.</p>
    </div>
    <h2 style="font-size: 20px; font-weight: 700; margin-bottom: 15px;">Summary</h2>
    <p style="font-size: 16px; margin-bottom: 30px;">
      Link Health: ${healthScore}<br>
      Total Links: ${summary.total}<br>
      OK: ${summary.ok}<br>
      Redirects: ${summary.redirects}<br>
      Broken: ${summary.broken}<br>
      Risky: ${summary.risky}<br>
      <i>Recommendations: Fix broken links to improve SEO and user experience. Verify risky links with Google Safe Browsing.</i>
    </p>
    <h2 style="font-size: 20px; font-weight: 700; margin-bottom: 15px;">Scan Results</h2>
    <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
      <thead>
        <tr style="background: #E2E8F0;">
          <th style="padding: 10px; border: 2px solid #CBD5E1; text-align: left;">URL</th>
          <th style="padding: 10px; border: 2px solid #CBD5E1; text-align: left;">Status</th>
          <th style="padding: 10px; border: 2px solid #CBD5E1; text-align: left;">Details</th>
          <th style="padding: 10px; border: 2px solid #CBD5E1; text-align: left;">Insights</th>
          <th style="padding: 10px; border: 2px solid #CBD5E1; text-align: left;">Timestamp</th>
        </tr>
      </thead>
      <tbody>
        ${results.map(result => `
          <tr>
            <td style="padding: 10px; border: 2px solid #CBD5E1;">${result.url}</td>
            <td style="padding: 10px; border: 2px solid #CBD5E1;">${result.status}</td>
            <td style="padding: 10px; border: 2px solid #CBD5E1;">${result.details || '-'}</td>
            <td style="padding: 10px; border: 2px solid #CBD5E1;">${result.insights}</td>
            <td style="padding: 10px; border: 2px solid #CBD5E1;">${result.timestamp}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;

  const opt = {
    margin: 0.75,
    filename: 'LinkCheckr_Pro_Scan_Report.pdf',
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
  };

  html2pdf().from(exportContent).set(opt).save();
}
